### ISSUE TITLE
Empty ByteBuffer from Golang leads to "invalid pointer found on stack"

### ISSUE THREAD

**Issue by appaquet** [mozilla/ffi-support#7]
First, thanks for the great library! It was very helpful in quickly integrating a new Rust component into our existing Go project.

Unfortunately, we stumbled on a bug when a Rust method returns an empty ByteBuffer. It may lead to a Golang runtime panic with a "invalid pointer found on stack" error (thrown [here](https://github.com/golang/go/blob/0d0193409492b96881be6407ad50123e3557fdfb/src/runtime/stack.go#L619)).

After analysis, from what I gather, when Go migrates a goroutine stack to another thread, it validates pointers that are stored on the stack. In Rust, an empty `Vec` has a non-zero pointer with a value set to `std::ptr::Unique::dangling()`, which fails to validate once in Go.

I have an easy fix [here](https://github.com/mozilla/ffi-support/compare/main...zia-ai:golang-invalid-ptr), but I decided to open this bug first to gather your feedback on if this kind of language specific code can be merged. If so, I'll open a PR.

**Comment by mhammond** [comment]
This looks reasonable to me and given the patch is small I think we'd take it. For your own future reference, we will probably push back on too many changes to support Go because Mozilla considers this repo soft-deprecated and is investing more time and effort into [uniffi](https://github.com/mozilla/uniffi-rs/) - (and a quick look shows it probably has the same problem [here](https://github.com/mozilla/uniffi-rs/blob/e109ef9241fe6f6375471bc29f62b511a70907a5/uniffi/src/ffi/rustbuffer.rs#L138) :)

(As a nit on the patch, where you wrote `std::ptr::Unique::dangling()` did you mean `std::ptr::Unique::empty()`? I can't see a method named `dangling()` while `empty()` documents itself as "Creates a new Unique that is dangling, but well-aligned.")

**Comment by appaquet** [comment]
Oh, didn't know about uniffi. I'll have a look at it, but I don't think it would have been of help since there is no generator for Golang.

As for `std::ptr::Unique::dangling()`, it's not exposed in the doc, but it's referenced in `RawVec` [here](https://github.com/rust-lang/rust/blob/master/library/alloc/src/raw_vec.rs#L35) and [here](https://github.com/rust-lang/rust/blob/master/library/alloc/src/raw_vec.rs#L135) and defined [here](https://github.com/rust-lang/rust/blob/master/library/core/src/ptr/unique.rs#L72).

I'll open the PR.
